import { serverSideTranslations as _serverSideTranslations } from "next-i18next/serverSideTranslations"
import path from "path"

const i18nConfig = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "ar", "ru"],
    localeDetection: false,
  },
  defaultNS: "common",
  // fallbackNS lets useTranslation("common") components resolve keys that now live
  // in page/section-scoped namespaces (split out of the old monolithic common.json)
  // WITHOUT editing any component — provided the page loads that namespace.
  // GENERATED by scripts/i18n-gen.mjs — do not edit by hand.
  fallbackNS: ["common","fleetcontent","loccontent","comparecontent","servicespages","page_about","page_blog","page_faq","page_pricing","page_terms","page_privacy","page_booking","page_gallery","page_testimonials","sb_fleet-cullinan","sb_fleet-dawn","sb_fleet-ghost","sb_fleet-phantom","sb_fleet-wraith","sb_home","sb_luxury-car-rental-dubai","sb_pricing","sb_services-airport-transfer","sb_services-hourly","sb_services-wedding"],
  localePath: path.resolve("./public/locales"),
  reloadOnPrerender: process.env.NODE_ENV === "development",
  react: { useSuspense: false },
}

// Bundled translations — webpack inlines require() at build time so JSON is embedded
// in the Cloudflare Worker bundle. GENERATED by scripts/i18n-gen.mjs.
const bundled: Record<string, Record<string, any>> = {
  en: {
    "common": require("../../public/locales/en/common.json"),
    "seo": require("../../public/locales/en/seo.json"),
    "navigation": require("../../public/locales/en/navigation.json"),
    "services": require("../../public/locales/en/services.json"),
    "fleet": require("../../public/locales/en/fleet.json"),
    "locations": require("../../public/locales/en/locations.json"),
    "compare": require("../../public/locales/en/compare.json"),
    "footer": require("../../public/locales/en/footer.json"),
    "pages": require("../../public/locales/en/pages.json"),
    "fleetcontent": require("../../public/locales/en/fleet-content.json"),
    "loccontent": require("../../public/locales/en/locations-content.json"),
    "comparecontent": require("../../public/locales/en/compare-content.json"),
    "servicespages": require("../../public/locales/en/services-pages.json"),
    "page_about": require("../../public/locales/en/pages/about.json"),
    "page_blog": require("../../public/locales/en/pages/blog.json"),
    "page_faq": require("../../public/locales/en/pages/faq.json"),
    "page_pricing": require("../../public/locales/en/pages/pricing.json"),
    "page_terms": require("../../public/locales/en/pages/terms.json"),
    "page_privacy": require("../../public/locales/en/pages/privacy.json"),
    "page_booking": require("../../public/locales/en/pages/booking.json"),
    "page_gallery": require("../../public/locales/en/pages/gallery.json"),
    "page_testimonials": require("../../public/locales/en/pages/testimonials.json"),
    "sb_fleet-cullinan": require("../../public/locales/en/seoblocks/fleet-cullinan.json"),
    "sb_fleet-dawn": require("../../public/locales/en/seoblocks/fleet-dawn.json"),
    "sb_fleet-ghost": require("../../public/locales/en/seoblocks/fleet-ghost.json"),
    "sb_fleet-phantom": require("../../public/locales/en/seoblocks/fleet-phantom.json"),
    "sb_fleet-wraith": require("../../public/locales/en/seoblocks/fleet-wraith.json"),
    "sb_home": require("../../public/locales/en/seoblocks/home.json"),
    "sb_luxury-car-rental-dubai": require("../../public/locales/en/seoblocks/luxury-car-rental-dubai.json"),
    "sb_pricing": require("../../public/locales/en/seoblocks/pricing.json"),
    "sb_services-airport-transfer": require("../../public/locales/en/seoblocks/services-airport-transfer.json"),
    "sb_services-hourly": require("../../public/locales/en/seoblocks/services-hourly.json"),
    "sb_services-wedding": require("../../public/locales/en/seoblocks/services-wedding.json"),
  },
  ar: {
    "common": require("../../public/locales/ar/common.json"),
    "seo": require("../../public/locales/ar/seo.json"),
    "navigation": require("../../public/locales/ar/navigation.json"),
    "services": require("../../public/locales/ar/services.json"),
    "fleet": require("../../public/locales/ar/fleet.json"),
    "locations": require("../../public/locales/ar/locations.json"),
    "compare": require("../../public/locales/ar/compare.json"),
    "footer": require("../../public/locales/ar/footer.json"),
    "pages": require("../../public/locales/ar/pages.json"),
    "fleetcontent": require("../../public/locales/ar/fleet-content.json"),
    "loccontent": require("../../public/locales/ar/locations-content.json"),
    "comparecontent": require("../../public/locales/ar/compare-content.json"),
    "servicespages": require("../../public/locales/ar/services-pages.json"),
    "page_about": require("../../public/locales/ar/pages/about.json"),
    "page_blog": require("../../public/locales/ar/pages/blog.json"),
    "page_faq": require("../../public/locales/ar/pages/faq.json"),
    "page_pricing": require("../../public/locales/ar/pages/pricing.json"),
    "page_terms": require("../../public/locales/ar/pages/terms.json"),
    "page_privacy": require("../../public/locales/ar/pages/privacy.json"),
    "page_booking": require("../../public/locales/ar/pages/booking.json"),
    "page_gallery": require("../../public/locales/ar/pages/gallery.json"),
    "page_testimonials": require("../../public/locales/ar/pages/testimonials.json"),
    "sb_fleet-cullinan": require("../../public/locales/ar/seoblocks/fleet-cullinan.json"),
    "sb_fleet-dawn": require("../../public/locales/ar/seoblocks/fleet-dawn.json"),
    "sb_fleet-ghost": require("../../public/locales/ar/seoblocks/fleet-ghost.json"),
    "sb_fleet-phantom": require("../../public/locales/ar/seoblocks/fleet-phantom.json"),
    "sb_fleet-wraith": require("../../public/locales/ar/seoblocks/fleet-wraith.json"),
    "sb_home": require("../../public/locales/ar/seoblocks/home.json"),
    "sb_luxury-car-rental-dubai": require("../../public/locales/ar/seoblocks/luxury-car-rental-dubai.json"),
    "sb_pricing": require("../../public/locales/ar/seoblocks/pricing.json"),
    "sb_services-airport-transfer": require("../../public/locales/ar/seoblocks/services-airport-transfer.json"),
    "sb_services-hourly": require("../../public/locales/ar/seoblocks/services-hourly.json"),
    "sb_services-wedding": require("../../public/locales/ar/seoblocks/services-wedding.json"),
  },
  ru: {
    "common": require("../../public/locales/ru/common.json"),
    "seo": require("../../public/locales/ru/seo.json"),
    "navigation": require("../../public/locales/ru/navigation.json"),
    "services": require("../../public/locales/ru/services.json"),
    "fleet": require("../../public/locales/ru/fleet.json"),
    "locations": require("../../public/locales/ru/locations.json"),
    "compare": require("../../public/locales/ru/compare.json"),
    "footer": require("../../public/locales/ru/footer.json"),
    "pages": require("../../public/locales/ru/pages.json"),
    "fleetcontent": require("../../public/locales/ru/fleet-content.json"),
    "loccontent": require("../../public/locales/ru/locations-content.json"),
    "comparecontent": require("../../public/locales/ru/compare-content.json"),
    "servicespages": require("../../public/locales/ru/services-pages.json"),
    "page_about": require("../../public/locales/ru/pages/about.json"),
    "page_blog": require("../../public/locales/ru/pages/blog.json"),
    "page_faq": require("../../public/locales/ru/pages/faq.json"),
    "page_pricing": require("../../public/locales/ru/pages/pricing.json"),
    "page_terms": require("../../public/locales/ru/pages/terms.json"),
    "page_privacy": require("../../public/locales/ru/pages/privacy.json"),
    "page_booking": require("../../public/locales/ru/pages/booking.json"),
    "page_gallery": require("../../public/locales/ru/pages/gallery.json"),
    "page_testimonials": require("../../public/locales/ru/pages/testimonials.json"),
    "sb_fleet-cullinan": require("../../public/locales/ru/seoblocks/fleet-cullinan.json"),
    "sb_fleet-dawn": require("../../public/locales/ru/seoblocks/fleet-dawn.json"),
    "sb_fleet-ghost": require("../../public/locales/ru/seoblocks/fleet-ghost.json"),
    "sb_fleet-phantom": require("../../public/locales/ru/seoblocks/fleet-phantom.json"),
    "sb_fleet-wraith": require("../../public/locales/ru/seoblocks/fleet-wraith.json"),
    "sb_home": require("../../public/locales/ru/seoblocks/home.json"),
    "sb_luxury-car-rental-dubai": require("../../public/locales/ru/seoblocks/luxury-car-rental-dubai.json"),
    "sb_pricing": require("../../public/locales/ru/seoblocks/pricing.json"),
    "sb_services-airport-transfer": require("../../public/locales/ru/seoblocks/services-airport-transfer.json"),
    "sb_services-hourly": require("../../public/locales/ru/seoblocks/services-hourly.json"),
    "sb_services-wedding": require("../../public/locales/ru/seoblocks/services-wedding.json"),
  },
}

export const serverSideTranslations = async (
  locale: string,
  namespaces?: string[]
) => {
  const ns = namespaces || ["common"]
  const lang = locale || "en"

  if (process.env.NODE_ENV === "development") {
    try {
      return await _serverSideTranslations(locale, ns, i18nConfig as any)
    } catch (error) {
      console.error("[i18n] Filesystem load failed in dev:", error)
    }
  }

  // Production: bundled only (no fs on Workers). No en-fallback duplication —
  // ar/ru have 100% key parity (verified by scripts/i18n-verify.mjs).
  const localeResources = bundled[lang] || bundled["en"]
  const store: Record<string, Record<string, any>> = {}
  store[lang] = {}
  for (const n of ns) store[lang][n] = localeResources[n] || {}

  return {
    _nextI18Next: { initialI18nStore: store, initialLocale: lang, ns, userConfig: i18nConfig },
  }
}
