"""Batch 7: Add phantom page-specific translation keys to common.json for all 6 languages"""
DATA = {
    "en": {"common": {"phantomPage": {
        "heroSubtitle": "Experience the pinnacle of luxury with Dubai's most prestigious vehicle. The Phantom delivers an unparalleled combination of craftsmanship, technology, and comfort.",
        "instantBooking": "Instant Booking",
        "freeCancellation": "Free Cancellation",
        "bestPriceGuarantee": "Best Price Guarantee",
        "happyClients": "Happy Clients",
        "googleRating": "Google Rating",
        "support": "Support",
        "deliveryTime": "Delivery Time",
        "since2010": "Since 2010",
        "inBusiness": "In Business",
        "pricingTitle": "Transparent Pricing & Instant Availability",
        "kmIncluded250": "250km included",
        "kmIncluded1750": "1,750km included",
        "kmIncluded5000": "5,000km included",
        "mostPopular": "MOST POPULAR",
        "availableNow": "Available Now - Instant Confirmation",
        "checkAvailability": "Check Real-Time Availability",
        "insuranceIncluded": "Insurance Included",
        "vatIncluded": "VAT Included",
        "noHiddenFees": "No Hidden Fees",
        "freeDelivery": "Free Delivery",
        "featuresSubtitle": "Every detail crafted to perfection, every feature designed for your ultimate comfort",
        "chatPhone": "Chat: +971 55 816 4922"
    }}},
    "ar": {"common": {"phantomPage": {
        "heroSubtitle": "استمتع بقمة الفخامة مع أرقى سيارات دبي. تقدم فانتوم مزيجاً لا مثيل له من الحرفية والتكنولوجيا والراحة.",
        "instantBooking": "حجز فوري",
        "freeCancellation": "إلغاء مجاني",
        "bestPriceGuarantee": "ضمان أفضل سعر",
        "happyClients": "عملاء سعداء",
        "googleRating": "تقييم جوجل",
        "support": "الدعم",
        "deliveryTime": "وقت التوصيل",
        "since2010": "منذ 2010",
        "inBusiness": "في الخدمة",
        "pricingTitle": "أسعار شفافة وتوفر فوري",
        "kmIncluded250": "250 كم مشمولة",
        "kmIncluded1750": "1,750 كم مشمولة",
        "kmIncluded5000": "5,000 كم مشمولة",
        "mostPopular": "الأكثر طلباً",
        "availableNow": "متاح الآن - تأكيد فوري",
        "checkAvailability": "تحقق من التوفر الفوري",
        "insuranceIncluded": "تأمين مشمول",
        "vatIncluded": "ضريبة مشمولة",
        "noHiddenFees": "بدون رسوم خفية",
        "freeDelivery": "توصيل مجاني",
        "featuresSubtitle": "كل تفصيل مصنوع بإتقان، كل ميزة مصممة لراحتك المطلقة",
        "chatPhone": "تواصل: +971 55 816 4922"
    }}},
    "fr": {"common": {"phantomPage": {
        "heroSubtitle": "Vivez le summum du luxe avec le véhicule le plus prestigieux de Dubaï. La Phantom offre une combinaison inégalée de savoir-faire, de technologie et de confort.",
        "instantBooking": "Réservation instantanée",
        "freeCancellation": "Annulation gratuite",
        "bestPriceGuarantee": "Garantie meilleur prix",
        "happyClients": "Clients satisfaits",
        "googleRating": "Note Google",
        "support": "Support",
        "deliveryTime": "Délai de livraison",
        "since2010": "Depuis 2010",
        "inBusiness": "En activité",
        "pricingTitle": "Tarification transparente & disponibilité instantanée",
        "kmIncluded250": "250km inclus",
        "kmIncluded1750": "1 750km inclus",
        "kmIncluded5000": "5 000km inclus",
        "mostPopular": "LE PLUS POPULAIRE",
        "availableNow": "Disponible maintenant - Confirmation instantanée",
        "checkAvailability": "Vérifier la disponibilité en temps réel",
        "insuranceIncluded": "Assurance incluse",
        "vatIncluded": "TVA incluse",
        "noHiddenFees": "Sans frais cachés",
        "freeDelivery": "Livraison gratuite",
        "featuresSubtitle": "Chaque détail perfectionné, chaque caractéristique conçue pour votre confort ultime",
        "chatPhone": "Chat : +971 55 816 4922"
    }}},
    "ru": {"common": {"phantomPage": {
        "heroSubtitle": "Испытайте вершину роскоши с самым престижным автомобилем Дубая. Phantom сочетает непревзойдённое мастерство, технологии и комфорт.",
        "instantBooking": "Мгновенное бронирование",
        "freeCancellation": "Бесплатная отмена",
        "bestPriceGuarantee": "Гарантия лучшей цены",
        "happyClients": "Довольных клиентов",
        "googleRating": "Рейтинг Google",
        "support": "Поддержка",
        "deliveryTime": "Время доставки",
        "since2010": "С 2010 года",
        "inBusiness": "В бизнесе",
        "pricingTitle": "Прозрачные цены и мгновенная доступность",
        "kmIncluded250": "250 км включено",
        "kmIncluded1750": "1 750 км включено",
        "kmIncluded5000": "5 000 км включено",
        "mostPopular": "САМЫЙ ПОПУЛЯРНЫЙ",
        "availableNow": "Доступно сейчас — мгновенное подтверждение",
        "checkAvailability": "Проверить наличие в реальном времени",
        "insuranceIncluded": "Страховка включена",
        "vatIncluded": "НДС включён",
        "noHiddenFees": "Без скрытых платежей",
        "freeDelivery": "Бесплатная доставка",
        "featuresSubtitle": "Каждая деталь доведена до совершенства, каждая функция создана для вашего комфорта",
        "chatPhone": "Чат: +971 55 816 4922"
    }}},
    "zh": {"common": {"phantomPage": {
        "heroSubtitle": "体验迪拜最尊贵车辆的极致奢华。幻影融合了无与伦比的工艺、技术与舒适。",
        "instantBooking": "即时预订",
        "freeCancellation": "免费取消",
        "bestPriceGuarantee": "最优价格保证",
        "happyClients": "满意客户",
        "googleRating": "谷歌评分",
        "support": "全天支持",
        "deliveryTime": "送车时间",
        "since2010": "始于2010",
        "inBusiness": "持续运营",
        "pricingTitle": "透明定价，即时可用",
        "kmIncluded250": "含250公里",
        "kmIncluded1750": "含1,750公里",
        "kmIncluded5000": "含5,000公里",
        "mostPopular": "最受欢迎",
        "availableNow": "现在可用 - 即时确认",
        "checkAvailability": "查看实时可用性",
        "insuranceIncluded": "含保险",
        "vatIncluded": "含增值税",
        "noHiddenFees": "无隐藏费用",
        "freeDelivery": "免费送车",
        "featuresSubtitle": "每个细节精雕细琢，每项功能为您的极致舒适而设计",
        "chatPhone": "咨询：+971 55 816 4922"
    }}},
    "hi": {"common": {"phantomPage": {
        "heroSubtitle": "दुबई के सबसे प्रतिष्ठित वाहन के साथ लक्जरी के शिखर का अनुभव करें। फैंटम शिल्प कौशल, तकनीक और आराम का बेजोड़ संयोजन प्रदान करती है।",
        "instantBooking": "तुरंत बुकिंग",
        "freeCancellation": "मुफ्त रद्दीकरण",
        "bestPriceGuarantee": "सर्वोत्तम मूल्य गारंटी",
        "happyClients": "खुश ग्राहक",
        "googleRating": "गूगल रेटिंग",
        "support": "सहायता",
        "deliveryTime": "डिलीवरी समय",
        "since2010": "2010 से",
        "inBusiness": "व्यवसाय में",
        "pricingTitle": "पारदर्शी मूल्य निर्धारण और तत्काल उपलब्धता",
        "kmIncluded250": "250 किमी शामिल",
        "kmIncluded1750": "1,750 किमी शामिल",
        "kmIncluded5000": "5,000 किमी शामिल",
        "mostPopular": "सबसे लोकप्रिय",
        "availableNow": "अभी उपलब्ध - तत्काल पुष्टि",
        "checkAvailability": "रीयल-टाइम उपलब्धता जांचें",
        "insuranceIncluded": "बीमा शामिल",
        "vatIncluded": "VAT शामिल",
        "noHiddenFees": "कोई छिपी फीस नहीं",
        "freeDelivery": "मुफ्त डिलीवरी",
        "featuresSubtitle": "हर विवरण पूर्णता के साथ तैयार, हर सुविधा आपके परम आराम के लिए डिज़ाइन",
        "chatPhone": "चैट: +971 55 816 4922"
    }}}
}
