#!/usr/bin/env node
// Single source of truth for the i18n namespace manifest. Regenerates the bundled
// require() map + fallbackNS in serverSideTranslations.ts, syncs fallbackNS into
// _app.tsx and next-i18next.config.js, and repoints SeoContentBlock pages to their
// per-block namespace. Re-runnable.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
const ROOT = '/Users/ahmedsalem/Desktop/all my projects/rollsroycers.com'

const seoblocks = JSON.parse(readFileSync('/tmp/seoblock-list.json', 'utf8'))
// [ns, file, inFallbackNS]
const SEO_SECTIONS = ['home', 'fleet', 'services', 'locations', 'compare', 'other']
const MANIFEST = [
  ['common', 'common.json', true],
  ...SEO_SECTIONS.map((s) => ['seo_' + s, 'seo/' + s + '.json', true]),
  ['navigation', 'navigation.json', false],
  ['services', 'services.json', false],
  ['fleet', 'fleet.json', false],
  ['locations', 'locations.json', false],
  ['compare', 'compare.json', false],
  ['footer', 'footer.json', false],
  ['pages', 'pages.json', false],
  ['fleetcontent', 'fleet-content.json', true],
  ['loccontent', 'locations-content.json', true],
  ['comparecontent', 'compare-content.json', true],
  ['servicespages', 'services-pages.json', true],
  ['page_about', 'pages/about.json', true],
  ['page_blog', 'pages/blog.json', true],
  ['page_faq', 'pages/faq.json', true],
  ['page_pricing', 'pages/pricing.json', true],
  ['page_terms', 'pages/terms.json', true],
  ['page_privacy', 'pages/privacy.json', true],
  ['page_booking', 'pages/booking.json', true],
  ['page_gallery', 'pages/gallery.json', true],
  ['page_testimonials', 'pages/testimonials.json', true],
  ...seoblocks.map((b) => ['sb_' + b, 'seoblocks/' + b + '.json', true]),
]
const fallbackNS = MANIFEST.filter((m) => m[2]).map((m) => m[0])
const fbLiteral = JSON.stringify(fallbackNS)

// --- (1) serverSideTranslations.ts: bundled map + i18nConfig ---
const locBlock = (L) =>
  '  ' + L + ': {\n' +
  MANIFEST.map(([ns, f]) => `    "${ns}": require("../../public/locales/${L}/${f}"),`).join('\n') +
  '\n  },'
const bundled =
  'const bundled: Record<string, Record<string, any>> = {\n' +
  ['en', 'ar', 'ru'].map(locBlock).join('\n') + '\n}'
const sst = `import { serverSideTranslations as _serverSideTranslations } from "next-i18next/serverSideTranslations"
import path from "path"

const i18nConfig = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "ar", "ru"],
    localeDetection: false,
  },
  defaultNS: "common",
  // fallbackNS lets useTranslation("common") components resolve keys that now live
  // in page/section-scoped namespaces (split out of the old monolithic common.json)
  // WITHOUT editing any component — provided the page loads that namespace.
  // GENERATED by scripts/i18n-gen.mjs — do not edit by hand.
  fallbackNS: ${fbLiteral},
  localePath: path.resolve("./public/locales"),
  reloadOnPrerender: process.env.NODE_ENV === "development",
  react: { useSuspense: false },
}

// Bundled translations — webpack inlines require() at build time so JSON is embedded
// in the Cloudflare Worker bundle. GENERATED by scripts/i18n-gen.mjs.
${bundled}

export const serverSideTranslations = async (
  locale: string,
  namespaces?: string[]
) => {
  const ns = namespaces || ["common"]
  const lang = locale || "en"

  if (process.env.NODE_ENV === "development") {
    try {
      return await _serverSideTranslations(locale, ns, i18nConfig as any)
    } catch (error) {
      console.error("[i18n] Filesystem load failed in dev:", error)
    }
  }

  // Production: bundled only (no fs on Workers). No en-fallback duplication —
  // ar/ru have 100% key parity (verified by scripts/i18n-verify.mjs).
  const localeResources = bundled[lang] || bundled["en"]
  const store: Record<string, Record<string, any>> = {}
  store[lang] = {}
  for (const n of ns) store[lang][n] = localeResources[n] || {}

  return {
    _nextI18Next: { initialI18nStore: store, initialLocale: lang, ns, userConfig: i18nConfig },
  }
}
`
writeFileSync(join(ROOT, 'src/lib/serverSideTranslations.ts'), sst)

// --- (2) sync fallbackNS into _app.tsx and next-i18next.config.js ---
for (const f of ['src/pages/_app.tsx', 'next-i18next.config.js']) {
  const p = join(ROOT, f)
  let src = readFileSync(p, 'utf8')
  src = src.replace(/fallbackNS:\s*\[[^\]]*\]/, `fallbackNS: ${fbLiteral}`)
  writeFileSync(p, src)
}

// --- (3) repoint SeoContentBlock pages to their per-block namespace ---
const PAGE_BLOCK = {
  'index': 'home', 'pricing': 'pricing', 'luxury-car-rental-dubai': 'luxury-car-rental-dubai',
  'fleet/cullinan': 'fleet-cullinan', 'fleet/ghost': 'fleet-ghost', 'fleet/dawn': 'fleet-dawn',
  'fleet/wraith': 'fleet-wraith', 'fleet/phantom': 'fleet-phantom',
  'services/airport-transfer': 'services-airport-transfer', 'services/hourly-rental': 'services-hourly',
  'services/wedding': 'services-wedding',
}
let repointed = 0
for (const [pg, block] of Object.entries(PAGE_BLOCK)) {
  const p = join(ROOT, 'src/pages', pg + '.tsx')
  let src = readFileSync(p, 'utf8')
  if (src.includes("'seoblocks'")) { src = src.replace("'seoblocks'", `'sb_${block}'`); writeFileSync(p, src); repointed++ }
  else if (src.includes('"seoblocks"')) { src = src.replace('"seoblocks"', `"sb_${block}"`); writeFileSync(p, src); repointed++ }
  else if (!src.includes(`sb_${block}`)) console.log('  WARN: no seoblocks ns in', pg)
}
// --- (4) repoint every page that loads the 'seo' namespace to its seo_<section> ---
const sectionFor = (route) => {
  if (route === 'index') return 'home'
  if (route === 'fleet' || route.startsWith('fleet/')) return 'fleet'
  if (route === 'services' || route.startsWith('services/')) return 'services'
  if (route === 'locations' || route.startsWith('locations/')) return 'locations'
  if (route.startsWith('compare/')) return 'compare'
  return 'other'
}
const PAGES_DIR = join(ROOT, 'src/pages')
function pageFiles(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    if (statSync(p).isDirectory()) pageFiles(p, out)
    else if (/\.tsx$/.test(e) && !e.startsWith('_')) out.push(p)
  }
  return out
}
let seoRepointed = 0
for (const f of pageFiles(PAGES_DIR)) {
  let src = readFileSync(f, 'utf8')
  if (!/serverSideTranslations/.test(src)) continue
  const route = f.replace(PAGES_DIR + '/', '').replace(/\.tsx$/, '')
  const sec = 'seo_' + sectionFor(route)
  let next = src
  if (/(\[[^\]]*)(['"])seo\2/.test(next)) {            // only the standalone 'seo' ns token in the array
    next = next.replace(/(\[[^\]]*?)(['"])seo\2/, `$1$2${sec}$2`)
  }
  if (next !== src) { writeFileSync(f, next); seoRepointed++ }
}
console.log(`namespaces: ${MANIFEST.length} | fallbackNS: ${fallbackNS.length} | seoblocks pages: ${repointed} | seo pages repointed: ${seoRepointed}`)
console.log('fallbackNS:', fbLiteral)
