#!/usr/bin/env node
// Single source of truth for the i18n namespace manifest. Regenerates the bundled
// require() map + fallbackNS in serverSideTranslations.ts, syncs fallbackNS into
// _app.tsx and next-i18next.config.js, and repoints SeoContentBlock pages to their
// per-block namespace. Re-runnable.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
const ROOT = '/Users/ahmedsalem/Desktop/all my projects/rollsroycers.com'

const seoblocks = JSON.parse(readFileSync('/tmp/seoblock-list.json', 'utf8'))
// [ns, file, inFallbackNS]
const SEO_SECTIONS = ['home', 'fleet', 'services', 'locations', 'compare', 'other']
const SERVICES = ['corporate', 'wedding', 'airportTransfer', 'chauffeur', 'events', 'photoshoot', 'tours']
const MODELS = ['phantom', 'ghost', 'cullinan', 'dawn', 'wraith', 'spectre']
const LOCS = ['downtown', 'dubaiMarina', 'jbr', 'businessBay', 'difc', 'palmJumeirah']
const MANIFEST = [
  ['common', 'common.json', true],
  ...SEO_SECTIONS.map((s) => ['seo_' + s, 'seo/' + s + '.json', true]),
  ['navigation', 'navigation.json', false],
  ['services', 'services.json', false],
  ['fleet', 'fleet.json', false],
  ['locations', 'locations.json', false],
  ['compare', 'compare.json', false],
  ['footer', 'footer.json', false],
  ['pages', 'pages.json', false],
  // C3: per-service (sp_* BEFORE servicespages so real service content wins over stale common dups)
  ...SERVICES.map((s) => ['sp_' + s, 'services-pages/' + s + '.json', true]),
  ['servicespages', 'services-pages.json', true],
  // C3: per-model fleet + shared
  ...MODELS.map((m) => ['fc_' + m, 'fleet/' + m + '.json', true]),
  ['fc_shared', 'fleet/_shared.json', true],
  // light fleet data (name+description only) for pages that render fleet CARDS (home,
  // fleet listing, booking) — they don't need the full per-model specs/features/gallery.
  ['fleetcards', 'fleetcards.json', true],
  // C3: per-location + shared
  ...LOCS.map((x) => ['lc_' + x, 'locations/' + x + '.json', true]),
  ['lc_shared', 'locations/_shared.json', true],
  ['comparefleet', 'comparefleet.json', true],
  ['comparemain', 'comparemain.json', true],
  ['weatherrec', 'weatherrec.json', true],
  ['page_about', 'pages/about.json', true],
  ['page_blog', 'pages/blog.json', true],
  ['page_faq', 'pages/faq.json', true],
  ['page_pricing', 'pages/pricing.json', true],
  ['page_terms', 'pages/terms.json', true],
  ['page_privacy', 'pages/privacy.json', true],
  ['page_booking', 'pages/booking.json', true],
  ['page_gallery', 'pages/gallery.json', true],
  ['page_testimonials', 'pages/testimonials.json', true],
  ...seoblocks.map((b) => ['sb_' + b, 'seoblocks/' + b + '.json', true]),
]
const fallbackNS = MANIFEST.filter((m) => m[2]).map((m) => m[0])
const fbLiteral = JSON.stringify(fallbackNS)

// --- (1) serverSideTranslations.ts: bundled map + i18nConfig ---
const locBlock = (L) =>
  '  ' + L + ': {\n' +
  MANIFEST.map(([ns, f]) => `    "${ns}": () => require("../../public/locales/${L}/${f}"),`).join('\n') +
  '\n  },'
const bundled =
  'const bundled: Record<string, Record<string, () => any>> = {\n' +
  ['en', 'ar', 'ru'].map(locBlock).join('\n') + '\n}'
const sst = `import { serverSideTranslations as _serverSideTranslations } from "next-i18next/serverSideTranslations"
import path from "path"

const i18nConfig = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "ar", "ru"],
    localeDetection: false,
  },
  defaultNS: "common",
  // fallbackNS lets useTranslation("common") components resolve keys that now live
  // in page/section-scoped namespaces (split out of the old monolithic common.json)
  // WITHOUT editing any component — provided the page loads that namespace.
  // GENERATED by scripts/i18n-gen.mjs — do not edit by hand.
  fallbackNS: ${fbLiteral},
  localePath: path.resolve("./public/locales"),
  reloadOnPrerender: process.env.NODE_ENV === "development",
  react: { useSuspense: false },
}

// Bundled translations — webpack inlines each require() into the Worker bundle, but
// behind a thunk so the JSON for a namespace is only parsed when serverSideTranslations
// actually requests it. This keeps cold-start memory/CPU low on Cloudflare Workers
// (the 128MB/CPU limits are what trigger transient 1102s on heavy cold renders): a page
// that needs 7 namespaces parses 7, not all ${MANIFEST.length}. GENERATED by scripts/i18n-gen.mjs.
${bundled}

export const serverSideTranslations = async (
  locale: string,
  namespaces?: string[]
) => {
  const ns = namespaces || ["common"]
  const lang = locale || "en"

  if (process.env.NODE_ENV === "development") {
    try {
      return await _serverSideTranslations(locale, ns, i18nConfig as any)
    } catch (error) {
      console.error("[i18n] Filesystem load failed in dev:", error)
    }
  }

  // Production: bundled only (no fs on Workers). No en-fallback duplication —
  // ar/ru have 100% key parity (verified by scripts/i18n-verify.mjs).
  // Thunks are invoked lazily so only the requested namespaces are parsed/held in memory.
  const localeResources = bundled[lang] || bundled["en"]
  const store: Record<string, Record<string, any>> = {}
  store[lang] = {}
  for (const n of ns) { const load = localeResources[n]; store[lang][n] = load ? load() : {} }

  return {
    _nextI18Next: { initialI18nStore: store, initialLocale: lang, ns, userConfig: i18nConfig },
  }
}
`
writeFileSync(join(ROOT, 'src/lib/serverSideTranslations.ts'), sst)

// --- (2) sync fallbackNS into _app.tsx and next-i18next.config.js ---
for (const f of ['src/pages/_app.tsx', 'next-i18next.config.js']) {
  const p = join(ROOT, f)
  let src = readFileSync(p, 'utf8')
  src = src.replace(/fallbackNS:\s*\[[^\]]*\]/, `fallbackNS: ${fbLiteral}`)
  writeFileSync(p, src)
}

// --- (3) repoint SeoContentBlock pages to their per-block namespace ---
const PAGE_BLOCK = {
  'index': 'home', 'pricing': 'pricing', 'luxury-car-rental-dubai': 'luxury-car-rental-dubai',
  'fleet/cullinan': 'fleet-cullinan', 'fleet/ghost': 'fleet-ghost', 'fleet/dawn': 'fleet-dawn',
  'fleet/wraith': 'fleet-wraith', 'fleet/phantom': 'fleet-phantom',
  'services/airport-transfer': 'services-airport-transfer', 'services/hourly-rental': 'services-hourly',
  'services/wedding': 'services-wedding',
}
let repointed = 0
for (const [pg, block] of Object.entries(PAGE_BLOCK)) {
  const p = join(ROOT, 'src/pages', pg + '.tsx')
  let src = readFileSync(p, 'utf8')
  if (src.includes("'seoblocks'")) { src = src.replace("'seoblocks'", `'sb_${block}'`); writeFileSync(p, src); repointed++ }
  else if (src.includes('"seoblocks"')) { src = src.replace('"seoblocks"', `"sb_${block}"`); writeFileSync(p, src); repointed++ }
  else if (!src.includes(`sb_${block}`)) console.log('  WARN: no seoblocks ns in', pg)
}
// --- (4) repoint every page that loads the 'seo' namespace to its seo_<section> ---
const sectionFor = (route) => {
  if (route === 'index') return 'home'
  if (route === 'fleet' || route.startsWith('fleet/')) return 'fleet'
  if (route === 'services' || route.startsWith('services/')) return 'services'
  if (route === 'locations' || route.startsWith('locations/')) return 'locations'
  if (route.startsWith('compare/')) return 'compare'
  return 'other'
}
const PAGES_DIR = join(ROOT, 'src/pages')
function pageFiles(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    if (statSync(p).isDirectory()) pageFiles(p, out)
    else if (/\.tsx$/.test(e) && !e.startsWith('_')) out.push(p)
  }
  return out
}
let seoRepointed = 0
for (const f of pageFiles(PAGES_DIR)) {
  let src = readFileSync(f, 'utf8')
  if (!/serverSideTranslations/.test(src)) continue
  const route = f.replace(PAGES_DIR + '/', '').replace(/\.tsx$/, '')
  const sec = 'seo_' + sectionFor(route)
  let next = src
  if (/(\[[^\]]*)(['"])seo\2/.test(next)) {            // only the standalone 'seo' ns token in the array
    next = next.replace(/(\[[^\]]*?)(['"])seo\2/, `$1$2${sec}$2`)
  }
  if (next !== src) { writeFileSync(f, next); seoRepointed++ }
}
// --- (5) C3: repoint fleetcontent/loccontent to per-item ns, add sp_<svc> to service pages ---
const FC_ALL = [...MODELS.map((m) => 'fc_' + m), 'fc_shared']
const LC_ALL = [...LOCS.map((x) => 'lc_' + x), 'lc_shared']
const FLEET_PAGE = { 'fleet/phantom': ['fc_phantom'], 'fleet/ghost': ['fc_ghost'], 'fleet/cullinan': ['fc_cullinan'], 'fleet/dawn': ['fc_dawn'], 'fleet/wraith': ['fc_wraith'], 'fleet/spectre': ['fc_spectre'] }
const FLEET_ALL_PAGES = ['index', 'fleet', 'booking']
const LOC_PAGE = { 'locations/downtown-dubai': ['lc_downtown'], 'locations/dubai-marina': ['lc_dubaiMarina'], 'locations/jbr': ['lc_jbr'], 'locations/business-bay': ['lc_businessBay'], 'locations/difc': ['lc_difc'], 'locations/palm-jumeirah': ['lc_palmJumeirah'] }
const LOC_SHARED_PAGE = ['locations/jumeirah', 'locations/deira'] // use jumeirahPage/deiraPage in lc_shared
const LOC_ALL_PAGES = ['locations']
const SVC_PAGE = { 'services/wedding': 'wedding', 'services/corporate': 'corporate', 'services/airport-transfer': 'airportTransfer', 'services/chauffeur': 'chauffeur', 'services/events': 'events', 'services/photoshoot': 'photoshoot', 'services/tours': 'tours' }

const fcFor = (r) => FLEET_PAGE[r] ? [...FLEET_PAGE[r], 'fc_shared'] : FLEET_ALL_PAGES.includes(r) ? FC_ALL : null
const lcFor = (r) => LOC_PAGE[r] ? [...LOC_PAGE[r], 'lc_shared'] : LOC_SHARED_PAGE.includes(r) ? ['lc_shared'] : LOC_ALL_PAGES.includes(r) ? LC_ALL : null
let c3 = 0
for (const f of pageFiles(PAGES_DIR)) {
  let src = readFileSync(f, 'utf8')
  const m = src.match(/serverSideTranslations\(\s*[^,]+,\s*\[([^\]]*)\]/)
  if (!m) continue
  const route = f.replace(PAGES_DIR + '/', '').replace(/\.tsx$/, '')
  let nsList = m[1].split(',').map((s) => s.trim().replace(/['"]/g, '')).filter(Boolean)
  const before = nsList.join(',')
  if (nsList.includes('fleetcontent')) { nsList = nsList.filter((n) => n !== 'fleetcontent'); const add = fcFor(route) || FC_ALL; nsList.push(...add) }
  if (nsList.includes('loccontent')) { nsList = nsList.filter((n) => n !== 'loccontent'); const add = lcFor(route) || LC_ALL; nsList.push(...add) }
  if (SVC_PAGE[route]) nsList.push('sp_' + SVC_PAGE[route])
  nsList = [...new Set(nsList)].sort((a, b) => (a === 'common' ? -1 : b === 'common' ? 1 : a.localeCompare(b)))
  if (nsList.join(',') !== before) {
    const arr = '[' + nsList.map((n) => `'${n}'`).join(', ') + ']'
    src = src.replace(/(serverSideTranslations\(\s*[^,]+,\s*)\[[^\]]*\]/, `$1${arr}`)
    writeFileSync(f, src); c3++
  }
}
console.log(`namespaces: ${MANIFEST.length} | fallbackNS: ${fallbackNS.length} | seo pages: ${seoRepointed} | C3 pages repointed: ${c3}`)
console.log('fallbackNS:', fbLiteral)
